### PR TITLE
fix(types): declare $ type eхplicitly

### LINKED ISSUE #421: The typing for `$.verbose` has changed in v6.2.0
@antongolub @antonmedv as a result of PR https://github.com/google/zx/pull/417 for zx v6.2.0, `$.verbose` now has type number rather than `boolean` as implied Readme.md (so `$.verbose = false` nolonger works unless you hack the typescript).

### PR DESCRIPTION
**Pull request by antongolub**
Fixes #421

### CODE REVIEW

**Comment by somombo** [comment]
I went with something like 
```typescript
export const $: Options & typeof _$ = _$
```

But lgtm!

File: src/context.ts [hunk 1]
```diff
@@ -13,6 +13,7 @@
 // limitations under the License.
 
 import { AsyncLocalStorage } from 'node:async_hooks'
+import { spawn} from 'node:child_process'
```
Comment (antonmedv) [inline src/context.ts:16]: npm run fmt
