### PR TITLE
Use inherited stdin instead of piped

### LINKED ISSUE #191: Error: the input device is not a TTY
```js
#!/usr/bin/env zx

await $`docker run --rm -ti ubuntu bash`;


```
## Expected Behavior

success

## Actual Behavior

Error: the input device is not a TTY

## Specifications

- Version: zx version 2.0.0
- Platform: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by antonmedv**
Fixes #191 

This PR refactors ProcessPromise. 

Now call $ does not create the child process. then() creates child process.

### CODE REVIEW

File: index.mjs [hunk 1]
```diff
@@ -44,19 +45,26 @@ export function $(pieces, ...args) {
...
+      shell: typeof shell === 'string' ? shell : true,
+      stdio: [promise._inheritStdin ? 'inherit' : 'pipe', 'pipe', 'pipe'],
+      windowsHide: true,
+    })
+
     child.on('exit', code => {
       child.on('close', () => {
-        if (piped) process.stdin.unpipe(child.stdin)
         let output = new ProcessOutput({
           code, stdout, stderr, combined,
```
Comment (antongolub) [inline index.mjs:69]: `combined`, `message` props are not declared`ProcessOutput` iface.

Comment (antonmedv) [reply index.mjs:69]: Yes, `message` goes to the parent class. And `combined` is used inside toString() func.

File: index.mjs [hunk 2]
```diff
@@ -44,19 +45,26 @@ export function $(pieces, ...args) {
...
+    if (promise.child) return
+    if (promise._prerun) promise._prerun()
+    if (verbose) {
+      printCmd(cmd)
+    }
+
+    let child = spawn(prefix + cmd, {
+      cwd,
+      shell: typeof shell === 'string' ? shell : true,
+      stdio: [promise._inheritStdin ? 'inherit' : 'pipe', 'pipe', 'pipe'],
```
Comment (huaziHear) [inline index.mjs:62]: Why use 'inherit' instead of 'pipe' for this parameter.

in cases like this, errors are reported：
```
#!/usr/bin/env zx
const sleep = () => new Promise((resolve) => setTimeout(resolve, 1000));

let p = $`read var; echo "$var";`

await sleep();

p.stdin.write('Hello, stdin!\n')  //  p.stdin is null
```

**Review by huaziHear — COMMENTED** [review]
Sorry, I'm a little confused about the logic.

File: index.mjs (hunk 2 above)
Comment (antonmedv) [reply index.mjs:62]: So, now zx comes with piped stdin by default.
