### PR TITLE
fix: omit redundant yaml API extras

### LINKED ISSUE #863: YAML.parseAllDocuments is no longer accessible
### Expected Behavior
https://stackblitz.com/edit/zx7-2-3-yaml?file=src/main.ts&terminal=dev
```js
import { YAML } from 'zx'
YAML.parseAllDocuments() // this function is accessible
```

### Actual Behavior
https://stackblitz.com/edit/zx-8-1-3-yaml?file=src/main.ts&terminal=dev
```js
import { YAML } from 'zx'
YAML.parseAllDocuments() // this function is not accessible
```

### Steps to Reproduce

1. Update from `7.2.3` to `8.1.3`.

### Specifications

- zx version:  8.1.3
- Platform: macos
- Runtime: node

### PR DESCRIPTION
**Pull request by antongolub**
* Remove redundant (undocumented) YAML API extras
* Override yaml pkg entry point from cjs to esm: reduce vendor bundle size by ~65Kb

Fixes #863 

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

File: scripts/build-js.mjs [hunk 1]
```diff
@@ -64,6 +66,12 @@ const entryPoints = entry.includes('*')
 const _bundle = bundle !== 'none' && !process.argv.includes('--no-bundle')
 const _external = _bundle ? external.split(',') : undefined // https://github.com/evanw/esbuild/issues/1466
 
+const plugins = [
+  esbuildResolvePlugin({
+    yaml: path.resolve(__dirname, '../node_modules/yaml/browser'),
```
Comment (antongolub) [inline scripts/build-js.mjs:71]: Workaround for https://github.com/eemeli/yaml/pull/560
